// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dPOG6YvooIDu3uCIIgvmNRlW1HJ4hco',
    appId: '1:375592809232:web:547a24a1e3d121e57feb95',
    messagingSenderId: '375592809232',
    projectId: 'chatemergency-a6b0b',
    authDomain: 'chatemergency-a6b0b.firebaseapp.com',
    storageBucket: 'chatemergency-a6b0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-O3PVCzMSgRzmnw3fKvOnLFlom2q6kQ',
    appId: '1:375592809232:android:58ded386b1634e517feb95',
    messagingSenderId: '375592809232',
    projectId: 'chatemergency-a6b0b',
    storageBucket: 'chatemergency-a6b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD0ayI-sTHIedeB8dZvAS8QOpMc-UN8GU',
    appId: '1:375592809232:ios:d0d57558bad8f05b7feb95',
    messagingSenderId: '375592809232',
    projectId: 'chatemergency-a6b0b',
    storageBucket: 'chatemergency-a6b0b.appspot.com',
    iosBundleId: 'com.example.emergencychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD0ayI-sTHIedeB8dZvAS8QOpMc-UN8GU',
    appId: '1:375592809232:ios:b5803eec94a4ed067feb95',
    messagingSenderId: '375592809232',
    projectId: 'chatemergency-a6b0b',
    storageBucket: 'chatemergency-a6b0b.appspot.com',
    iosBundleId: 'com.example.emergencychat.RunnerTests',
  );
}
