// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyXsiOkDoCHYvfa54s6OHHT5-CF-jwSwQ',
    appId: '1:394387019234:web:bb82c03788753b11eed5bb',
    messagingSenderId: '394387019234',
    projectId: 'emergencyapp-dddfc',
    authDomain: 'emergencyapp-dddfc.firebaseapp.com',
    databaseURL: 'https://emergencyapp-dddfc-default-rtdb.firebaseio.com',
    storageBucket: 'emergencyapp-dddfc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTtaMqFJKwWgeBSBj5UtEOruH3UcG3DZo',
    appId: '1:394387019234:android:15508db5f5833b76eed5bb',
    messagingSenderId: '394387019234',
    projectId: 'emergencyapp-dddfc',
    databaseURL: 'https://emergencyapp-dddfc-default-rtdb.firebaseio.com',
    storageBucket: 'emergencyapp-dddfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE8VfyD-1_RmUdqzP75EZ6fVoXY75fcuY',
    appId: '1:394387019234:ios:62cc4ec744d564dbeed5bb',
    messagingSenderId: '394387019234',
    projectId: 'emergencyapp-dddfc',
    databaseURL: 'https://emergencyapp-dddfc-default-rtdb.firebaseio.com',
    storageBucket: 'emergencyapp-dddfc.appspot.com',
    iosClientId: '394387019234-mmabpqn4d8jsd74lrv238mpkci4m8siu.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE8VfyD-1_RmUdqzP75EZ6fVoXY75fcuY',
    appId: '1:394387019234:ios:de4a5f106d99d595eed5bb',
    messagingSenderId: '394387019234',
    projectId: 'emergencyapp-dddfc',
    databaseURL: 'https://emergencyapp-dddfc-default-rtdb.firebaseio.com',
    storageBucket: 'emergencyapp-dddfc.appspot.com',
    iosClientId: '394387019234-5p5e6f7u16naspf558iirbqpo23ggmvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyapp.RunnerTests',
  );
}
